# Dataset
train_db_name: VOCSegmentation
val_db_name: VOCSegmentation
val_db_kwargs:
  batch_size: 10
num_workers: 4

# Model
backbone: resnet18
backbone_kwargs:
   dilated: True
   pretrained: True 
model_kwargs:
   ndim: 32
   head: linear
   upsample: True
   use_classification_head: True
   use_cluster_head: True
loss_coeff:
   contrastive: 1
   saliency: 1
   local_contrastive: 0
   cluster: 0
   consistency: 0.1

local_contrastive_kwargs:
   num_negatives:  48
   kernel: 3

cluster_kwargs:
   C: 20
   smooth_prob: True
   smooth_coeff: 0.1
   entropy_coeff: 5

consistency_kwargs:
   type: l2norm

head: 'deeplab'
freeze_layer: 'none'
pretraining: /content/drive/MyDrive/UCS_local/pretrained_result/VOCSegmentation_supervised_saliency_model/checkpoint.pth.tar # Change this
kmeans_eval: True
