# Dataset
train_db_name: VOCSegmentation
val_db_name: VOCSegmentation
val_db_kwargs:
  batch_size: 10
num_workers: 4

inveqv_version: 0

# Model
backbone: resnet18
backbone_kwargs:
   dilated: True
   pretrained: True 
model_kwargs:
   ndim: 32
   head: linear
   upsample: True
   use_classification_head: True

head: 'deeplab'
freeze_layer: 'none'
pretraining: /content/drive/MyDrive/UCS_local/pretrained_result/VOCSegmentation_unsupervised_saliency_model/checkpoint.pth.tar # Change this.
kmeans_eval: True
