# Dataset
train_db_name: VOCSegmentation
val_db_name: VOCSegmentation
val_db_kwargs:
  batch_size: 10
num_workers: 4

# Model
backbone: 'resnet18'
backbone_kwargs:
   dilated: True
   pretrained: True
model_kwargs:
   ndim: 32
   head: linear
   upsample: True
   use_classification_head: True
   use_attention_head: True

loss_coeff:
   contrastive: 1
   saliency: 1
   inveqv: 1
   mean: 0
   attention: 0

inveqv_kwargs:
   type: l2

mean_pixel_kwargs:
   type: mean
   
head: 'deeplab'
freeze_layer: 'none'
pretraining: /content/drive/MyDrive/UCS_local/pretrained_result/VOCSegmentation_unsupervised_saliency_model/checkpoint.pth.tar # Change this.
kmeans_eval: True

# Retrieval kwargs
retrieval_kwargs:
   ignore_classes: ['bicycle', 'bird', 'boat', 'chair', 'diningtable', 'dog', 'horse', 'motorbike', 'pottedplant', 'sheep', 'sofa', 'train', 'tvmonitor']
